version: "3"

services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /home/tadmin/valheim-server/config:/config
      - /home/tadmin/valheim-server/data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - /home/tadmin/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
